kernel-headers: 6.12.0 -> 6.12.7
This fixes a build problem with bpftools which used to fail with

```
/build/linux-6.12/tools/include/asm/../../arch/riscv/include/asm/barrier.h:13:10:
fatal error: asm/fence.h: No such file or directory
```

This change causes a mass rebuild.